-- Number of candidates
SELECT 
    PARTY, COUNT(*) AS NO_OF_CANDIDATES
FROM
    GENERAL_ELECTION_2024_RESULTS
WHERE
    CANDIDATE <> 'NOTA'
GROUP BY PARTY
ORDER BY NO_OF_CANDIDATES DESC;

-- Number of votes
SELECT 
    SUM(VOTES) AS NO_OF_VOTES
FROM
    GENERAL_ELECTION_2024_RESULTS;
    
-- Number of candidates
SELECT 
    COUNT(*) AS NO_OF_CANDIDATES
FROM
    GENERAL_ELECTION_2024_RESULTS
WHERE
    CANDIDATE <> 'NOTA';