-- Number of candidates
-- Number of candidates by party and state
SELECT 
    STATE, PARTY, COUNT(*) AS NO_OF_CANDIDATES
FROM
    ASSEMBLY_ELECTIONS_OCT2024
WHERE
    CANDIDATE <> 'NOTA'
GROUP BY STATE, PARTY
ORDER BY STATE ASC, NO_OF_CANDIDATES DESC;

-- Number of votes by state
SELECT 
    STATE, SUM(VOTES) AS NO_OF_VOTES
FROM
    ASSEMBLY_ELECTIONS_OCT2024
GROUP BY STATE
ORDER BY STATE ASC;

-- Number of candidates by state
SELECT 
    STATE, COUNT(*) AS NO_OF_CANDIDATES
FROM
    ASSEMBLY_ELECTIONS_OCT2024
WHERE
    CANDIDATE <> 'NOTA'
GROUP BY STATE
ORDER BY STATE ASC;