-- Maximum votes for a candidate
SELECT 
    CANDIDATE, PARTY, CONSTITUENCY, STATE, VOTES
FROM
    GENERAL_ELECTION_2024_RESULTS
ORDER BY VOTES DESC;

-- Max votes of winning candidates
SELECT 
    t.CANDIDATE,
    t.PARTY,
    t.CONSTITUENCY,
    t.STATE,
    t.VOTES AS WINNER_VOTES
FROM
    GENERAL_ELECTION_2024_RESULTS t
        JOIN
    (SELECT 
        STATE, CONSTITUENCY, MAX(VOTES) AS MAX_VOTES
    FROM
        GENERAL_ELECTION_2024_RESULTS
    GROUP BY STATE , CONSTITUENCY) sub ON t.STATE = sub.STATE
        AND t.CONSTITUENCY = sub.CONSTITUENCY
        AND t.VOTES = sub.MAX_VOTES
ORDER BY VOTES DESC;

-- Least votes for a winning candidate
SELECT 
    t.CANDIDATE AS CANDIDATE,
    t.PARTY AS PARTY,
    t.CONSTITUENCY AS CONSTITUENCY,
    t.STATE AS STATE,
    t.VOTES AS WINNER_VOTES
FROM
    GENERAL_ELECTION_2024_RESULTS t
        JOIN
    (SELECT 
        STATE, CONSTITUENCY, MAX(VOTES) AS MAX_VOTES
    FROM
        GENERAL_ELECTION_2024_RESULTS
    GROUP BY STATE , CONSTITUENCY) sub ON t.STATE = sub.STATE
        AND t.CONSTITUENCY = sub.CONSTITUENCY
        AND t.VOTES = sub.MAX_VOTES
ORDER BY WINNER_VOTES ASC;

-- Max votes for a losing candidate
SELECT 
    t2.CANDIDATE AS CANDIDATE,
    t2.PARTY AS PARTY,
    t2.CONSTITUENCY AS CONSTITUENCY,
    t2.STATE AS STATE,
    t2.VOTES AS RUNNER_VOTES
FROM
    GENERAL_ELECTION_2024_RESULTS t2
        JOIN
    (SELECT 
        t.STATE, t.CONSTITUENCY, MAX(t.VOTES) AS RUNNER_VOTES
    FROM
        GENERAL_ELECTION_2024_RESULTS t
    JOIN (SELECT 
        STATE, CONSTITUENCY, MAX(VOTES) AS MAX_VOTES
    FROM
        GENERAL_ELECTION_2024_RESULTS
    GROUP BY STATE , CONSTITUENCY) sub ON t.STATE = sub.STATE
        AND t.CONSTITUENCY = sub.CONSTITUENCY
        AND t.VOTES < sub.MAX_VOTES
    GROUP BY t.STATE , t.CONSTITUENCY) sub2 ON t2.STATE = sub2.STATE
        AND t2.CONSTITUENCY = sub2.CONSTITUENCY
        AND t2.VOTES = sub2.RUNNER_VOTES
ORDER BY RUNNER_VOTES DESC;

-- Candidates winning by Max/Min margin
SELECT 
    c1.STATE, 
    c1.CONSTITUENCY,
    c1.CANDIDATE AS WINNER, 
    c1.PARTY AS WINNER_PARTY, 
    c1.VOTES AS WINNER_VOTES, 
    c2.CANDIDATE AS RUNNER_UP, 
    c2.PARTY AS RUNNER_UP_PARTY, 
    c2.VOTES AS RUNNER_UP_VOTES, 
    (c1.VOTES - c2.VOTES) AS VOTE_DIFFERENCE
FROM 
    (SELECT 
        STATE, 
        CONSTITUENCY, 
        CANDIDATE, 
        PARTY, 
        VOTES,
        CODE,
        ROW_NUMBER() OVER (PARTITION BY STATE, CONSTITUENCY ORDER BY VOTES DESC) AS rn
     FROM GENERAL_ELECTION_2024_RESULTS
    ) c1
JOIN 
    (SELECT 
        STATE, 
        CONSTITUENCY, 
        CANDIDATE, 
        PARTY, 
        VOTES,
        ROW_NUMBER() OVER (PARTITION BY STATE, CONSTITUENCY ORDER BY VOTES DESC) AS rn
     FROM GENERAL_ELECTION_2024_RESULTS
    ) c2
ON c1.STATE = c2.STATE AND c1.CONSTITUENCY = c2.CONSTITUENCY AND c1.rn = 1 AND c2.rn = 2
ORDER BY VOTE_DIFFERENCE ASC;