-- Max Total Votes in a Constituency
-- Constituency with maximum votes
SELECT 
    CONSTITUENCY, STATE, SUM(VOTES) AS TOTAL_VOTES
FROM
    assembly_elections_nov2025
GROUP BY STATE, CONSTITUENCY
ORDER BY STATE ASC, TOTAL_VOTES DESC;

-- Min Total Votes Constituency
SELECT 
    CONSTITUENCY, STATE, SUM(VOTES) AS TOTAL_VOTES
FROM
    assembly_elections_nov2025
GROUP BY STATE, CONSTITUENCY
ORDER BY STATE ASC, TOTAL_VOTES ASC;

-- Max candidates in a Constituency
SELECT 
    CONSTITUENCY, STATE, COUNT(CANDIDATE) AS NO_OF_CANDIDATES
FROM
    assembly_elections_nov2025
GROUP BY STATE, CONSTITUENCY
ORDER BY STATE ASC, NO_OF_CANDIDATES DESC;

-- Least candidates in a Constituency
SELECT 
    CONSTITUENCY, STATE, COUNT(CANDIDATE) AS NO_OF_CANDIDATES
FROM
    assembly_elections_nov2025
GROUP BY STATE, CONSTITUENCY
ORDER BY STATE ASC, NO_OF_CANDIDATES ASC;