-- All Parties
SELECT DISTINCT
    PARTY
FROM
    ASSEMBLY_ELECTIONS_OCT2024
WHERE
    PARTY NOT IN ('INDEPENDENT' , 'NOTA')
ORDER BY PARTY;

-- Gold Medals
SELECT
    STATE,
    PARTY,
    COUNT(*) AS SEATS_WON
FROM
    (SELECT
        STATE,
        CONSTITUENCY,
        PARTY,
        VOTES,
        ROW_NUMBER() OVER (PARTITION BY STATE, CONSTITUENCY ORDER BY VOTES DESC) AS rn
     FROM ASSEMBLY_ELECTIONS_OCT2024
    ) AS ranked_results
WHERE rn = 1
GROUP BY STATE, PARTY
ORDER BY STATE ASC, SEATS_WON DESC;

-- Silver Medals
SELECT
    STATE,
    PARTY,
    COUNT(*) AS SILVER_MEDALS
FROM
    (SELECT
        STATE,
        CONSTITUENCY,
        PARTY,
        VOTES,
        ROW_NUMBER() OVER (PARTITION BY STATE, CONSTITUENCY ORDER BY VOTES DESC) AS rn
     FROM ASSEMBLY_ELECTIONS_OCT2024
    ) AS ranked_results
WHERE rn = 2
GROUP BY STATE, PARTY
ORDER BY STATE ASC, SILVER_MEDALS DESC;
