-- Cost per vote (Do best and worst)
SELECT 
    PARTY,
    TOTAL_COST,
    PARTY_VOTES,
    (TOTAL_COST / PARTY_VOTES) AS COST_PER_VOTE
FROM
    (SELECT 
        (COUNT(GER.CANDIDATE) * 9500000) AS TOTAL_COST,
            GER.PARTY AS PARTY,
            PARTY_VOTE_DETAILS.PARTY_VOTES AS PARTY_VOTES
    FROM
        GENERAL_ELECTION_2024_RESULTS GER
    JOIN (SELECT 
        PARTY, SUM(VOTES) AS PARTY_VOTES
    FROM
        GENERAL_ELECTION_2024_RESULTS
    GROUP BY PARTY) AS PARTY_VOTE_DETAILS ON GER.PARTY = PARTY_VOTE_DETAILS.PARTY
    GROUP BY GER.PARTY) COST_ANALYSIS
ORDER BY COST_PER_VOTE ASC;

-- Strike Rate - Best
SELECT
    p.PARTY,
    p.SEATS_PARTICIPATED,
    w.SEATS_WON,
    (w.SEATS_WON / p.SEATS_PARTICIPATED * 100) AS SUCCESS_RATIO
FROM
    (SELECT
        PARTY,
        COUNT(DISTINCT CONCAT(STATE, '_', CONSTITUENCY)) AS SEATS_PARTICIPATED
     FROM GENERAL_ELECTION_2024_RESULTS
     GROUP BY PARTY
    ) p
LEFT JOIN
    (SELECT
        PARTY,
        COUNT(*) AS SEATS_WON
     FROM
        (SELECT
            STATE,
            CONSTITUENCY,
            PARTY,
            VOTES,
            ROW_NUMBER() OVER (PARTITION BY STATE, CONSTITUENCY ORDER BY VOTES DESC) AS rn
         FROM GENERAL_ELECTION_2024_RESULTS
        ) ranked_results
     WHERE rn = 1
     GROUP BY PARTY
    ) w
ON p.PARTY = w.PARTY
ORDER BY SUCCESS_RATIO DESC, SEATS_PARTICIPATED DESC;

-- Strike Rate - Worst (at least 1 win)
SELECT
    p.PARTY,
    p.SEATS_PARTICIPATED,
    w.SEATS_WON,
    (w.SEATS_WON / p.SEATS_PARTICIPATED * 100) AS SUCCESS_RATIO
FROM
    (SELECT
        PARTY,
        COUNT(DISTINCT CONCAT(STATE, '_', CONSTITUENCY)) AS SEATS_PARTICIPATED
     FROM GENERAL_ELECTION_2024_RESULTS
     GROUP BY PARTY
    ) p
LEFT JOIN
    (SELECT
        PARTY,
        COUNT(*) AS SEATS_WON
     FROM
        (SELECT
            STATE,
            CONSTITUENCY,
            PARTY,
            VOTES,
            ROW_NUMBER() OVER (PARTITION BY STATE, CONSTITUENCY ORDER BY VOTES DESC) AS rn
         FROM GENERAL_ELECTION_2024_RESULTS
        ) ranked_results
     WHERE rn = 1
     GROUP BY PARTY
    ) w
ON p.PARTY = w.PARTY
WHERE w.SEATS_WON >= 1
ORDER BY SUCCESS_RATIO ASC, SEATS_PARTICIPATED DESC;