-- Multiple seats participating candidates
SELECT 
    STATE,
    CANDIDATE,
    COUNT(DISTINCT CONSTITUENCY) AS CONSTITUENCY_COUNT
FROM
    ASSEMBLY_ELECTIONS_OCT2024
WHERE
    CANDIDATE <> 'NOTA'
GROUP BY STATE, CANDIDATE, PARTY
ORDER BY STATE ASC, CONSTITUENCY_COUNT DESC, CANDIDATE;

-- Multiple participation results
WITH candidate_participation AS (
    SELECT
        STATE,
        CANDIDATE,
        PARTY,
        COUNT(DISTINCT CONCAT(STATE, '_', CONSTITUENCY)) AS CONSTITUENCY_COUNT
    FROM ASSEMBLY_ELECTIONS_OCT2024
    GROUP BY STATE, CANDIDATE, PARTY
),
ranked_results AS (
    SELECT
        STATE,
        CONSTITUENCY,
        CANDIDATE,
        PARTY,
        VOTES,
        ROW_NUMBER() OVER (PARTITION BY STATE, CONSTITUENCY ORDER BY VOTES DESC) AS rn
    FROM ASSEMBLY_ELECTIONS_OCT2024
)
SELECT
    r.STATE,
    r.CANDIDATE,
    r.CONSTITUENCY,
    r.PARTY,
    CASE WHEN r.rn = 1 THEN 'WON' ELSE 'LOST' END AS RESULT
FROM
    ranked_results r
JOIN
    candidate_participation cp
ON
    r.STATE = cp.STATE AND r.CANDIDATE = cp.CANDIDATE AND r.PARTY = cp.PARTY
WHERE
    cp.CONSTITUENCY_COUNT > 1 AND r.CANDIDATE <> 'NOTA'
ORDER BY
    r.STATE ASC, RESULT DESC, r.PARTY, r.CANDIDATE;
