WITH ranked_results AS (
    SELECT
        STATE,
        CONSTITUENCY,
        CANDIDATE,
        PARTY,
        VOTES,
        ROW_NUMBER() OVER (PARTITION BY STATE, CONSTITUENCY ORDER BY VOTES DESC) AS rn
    FROM GENERAL_ELECTION_2024_RESULTS
),
winner_and_runner_up AS (
    SELECT
        r1.STATE,
        r1.CONSTITUENCY,
        r1.PARTY AS WINNING_PARTY,
        r1.VOTES AS WINNING_VOTES,
        r2.PARTY AS LOSING_PARTY,
        r2.VOTES AS LOSING_VOTES,
        (r1.VOTES - r2.VOTES) AS VOTE_DIFFERENCE
    FROM
        ranked_results r1
    JOIN
        ranked_results r2
    ON
        r1.STATE = r2.STATE AND r1.CONSTITUENCY = r2.CONSTITUENCY
    WHERE
        r1.rn = 1 AND r2.rn = 2
)
SELECT
    LOSING_PARTY,
    COUNT(CASE WHEN VOTE_DIFFERENCE < 500 THEN 1 END) AS "< 500",
    COUNT(CASE WHEN VOTE_DIFFERENCE < 2500 THEN 1 END) AS "< 2500",
    COUNT(CASE WHEN VOTE_DIFFERENCE < 5000 THEN 1 END) AS "< 5000",
    COUNT(CASE WHEN VOTE_DIFFERENCE < 10000 THEN 1 END) AS "< 10000",
    COUNT(CASE WHEN VOTE_DIFFERENCE < 15000 THEN 1 END) AS "< 15000",
    COUNT(CASE WHEN VOTE_DIFFERENCE < 25000 THEN 1 END) AS "< 25000",
    COUNT(CASE WHEN VOTE_DIFFERENCE < 50000 THEN 1 END) AS "< 50000"
FROM
    winner_and_runner_up
GROUP BY
    LOSING_PARTY
HAVING
    COUNT(CASE WHEN VOTE_DIFFERENCE < 500 THEN 1 END) > 0 OR
    COUNT(CASE WHEN VOTE_DIFFERENCE < 2500 THEN 1 END) > 0 OR
    COUNT(CASE WHEN VOTE_DIFFERENCE < 5000 THEN 1 END) > 0 OR
    COUNT(CASE WHEN VOTE_DIFFERENCE < 10000 THEN 1 END) > 0 OR
    COUNT(CASE WHEN VOTE_DIFFERENCE < 15000 THEN 1 END) > 0 OR
    COUNT(CASE WHEN VOTE_DIFFERENCE < 25000 THEN 1 END) > 0 OR
    COUNT(CASE WHEN VOTE_DIFFERENCE < 50000 THEN 1 END) > 0
ORDER BY
    LOSING_PARTY;
