CREATE TABLE `GENERAL_ELECTION_2024_RESULTS` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(10) NOT NULL,
  `STATE` varchar(100) NOT NULL,
  `CONSTITUENCY` varchar(100) NOT NULL,
  `CONSTITUENCY_ID` int(11) NOT NULL,
  `CANDIDATE` varchar(100) NOT NULL,
  `PARTY` varchar(100) NOT NULL,
  `EVM_VOTES` int(11) NOT NULL,
  `POSTAL_VOTES` int(11) NOT NULL,
  `VOTES` int(11) NOT NULL,
  `VOTE_PERCENTAGE` float(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `CANDIDATE` (`CANDIDATE`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=8795 DEFAULT CHARSET=latin1;

LOAD DATA LOCAL INFILE '/Users/arjun/Developer/haskell/elections/election_results.csv'
INTO TABLE GENERAL_ELECTION_2024_RESULTS
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

FLUSH TABLES GENERAL_ELECTION_2024_RESULTS;

Select * FROM GENERAL_ELECTION_2024_RESULTS;

Select COUNT(*) FROM GENERAL_ELECTION_2024_RESULTS;